apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api-compras
spec:
  ports:
    - port: 80
  selector:
    app: api-compras
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  labels:
    app: api-compras
spec:
  tls:
    - hosts:
        - api-compras.projects.helx.dev
      secretName: api-tls
  rules:
    - host: api-compras.projects.helx.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api-compras
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-compras
  template:
    metadata:
      labels:
        app: api-compras
    spec:
      containers:
        - name: api
          image: ghcr.io/helxdev/api-compras:$GITHUB_SHA
          ports:
            - containerPort: 80
