apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database-compras
spec:
  ports:
    - port: 1433
  selector:
    app: database-compras
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database-compras
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-compras
  template:
    metadata:
      labels:
        app: database-compras
    spec:
      containers:
        - name: database
          image: mcr.microsoft.com/mssql/server:2017-latest
          envFrom:
            - secretRef:
                name: database
          volumeMounts:
            - mountPath: '/var/opt/mssql'
              name: database
          ports:
            - containerPort: 1433
      volumes:
        - name: database
          persistentVolumeClaim:
            claimName: pvc-database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-database
  labels:
    app: database-compras
spec:
  accessModes:
    - ReadWriteOnce
  resorces:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
